name       : python-lsp-server
version    : 1.3.3
release    : 3
source     :
    - https://files.pythonhosted.org/packages/source/p/python-lsp-server/python-lsp-server-1.3.3.tar.gz : 1b48ccd8b70103522e8a8b9cb9ae1be2b27a5db0dfd661e7e44e6253ebefdc40
homepage   : https://github.com/python-lsp/python-lsp-server
license    : MIT
component  : programming.python
summary    : Python Language Server for the Language Server Protocol
description: |
    Fork of the python-language-server project, maintained by the Spyder IDE team and the community. This is a Python 3.6+ implementation of the Language Server Protocol.
builddeps  :
    - autopep8
    - flake8
    - matplotlib
    - pydocstyle
    - pylint
    - python-flaky
    - python-jedi
    - python-lsp-jsonrpc
    - python-pandas
    - python-pytest-cov
    - python-qtpy
    - python-rope
    - python-ujson
    - yapf
rundeps    :
    - autopep8
    - flake8
    - pydocstyle
    - pylint
    - python-jedi
    - python-lsp-jsonrpc
    - python-pluggy
    - python-rope
    - python-ujson
    - yapf
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
