name       : python-lsp-server
version    : 1.5.0
release    : 6
source     :
    - https://files.pythonhosted.org/packages/source/p/python-lsp-server/python-lsp-server-1.5.0.tar.gz : e5c094c19925022a27c4068f414b2bb653243f8fb0d768e39735289d7a89380d
homepage   : https://github.com/python-lsp/python-lsp-server
license    : MIT
component  : programming.python
summary    : Python Language Server for the Language Server Protocol
description: |
    Fork of the python-language-server project, maintained by the Spyder IDE team and the community. This is a Python 3.6+ implementation of the Language Server Protocol.
builddeps  :
    - autopep8              # check
    - flake8                # check
    - matplotlib            # check
    - pydocstyle            # check
    - pylint                # check
    - python-flaky          # check
    - python-jedi           # check
    - python-lsp-jsonrpc    # check
    - python-pandas         # check
    - python-pytest-cov     # check
    - python-qtpy           # check
    - python-rope           # check
    - python-setuptools-scm
    - python-ujson          # check
    - python-whatthepatch   # check
    - python-wheel
    - yapf                  # check
rundeps    :
    - autopep8
    - flake8
    - pydocstyle
    - pylint
    - python-jedi
    - python-lsp-jsonrpc
    - python-pluggy
    - python-rope
    - python-ujson
    - python-whatthepatch
    - yapf
setup      : |
    %patch -p1 < $pkgfiles/0001-Revert-moving-to-pyproject.toml.patch
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v -k 'not test_pyqt_completion'
