name       : python-lsp-server
version    : 1.7.0
release    : 9
source     :
    - https://files.pythonhosted.org/packages/source/p/python-lsp-server/python-lsp-server-1.7.0.tar.gz : 401ce78ea2e98cadd02d94962eb32c92879caabc8055b9a2f36d7ef44acc5435
homepage   : https://github.com/python-lsp/python-lsp-server
license    : MIT
component  : programming.python
summary    : Python Language Server for the Language Server Protocol
description: |
    Fork of the python-language-server project, maintained by the Spyder IDE team and the community. This is a Python 3.6+ implementation of the Language Server Protocol.
networking : yes
builddeps  :
    - autopep8              # check
    - flake8                # check
    - matplotlib            # check
    - pydocstyle            # check
    - pylint                # check
    - python-docstring-to-markdown
    - python-flaky          # check
    - python-jedi           # check
    - python-lsp-jsonrpc    # check
    - python-pandas         # check
    - python-pytest-cov     # check
    - python-qtpy           # check
    - python-rope           # check
    - python-setuptools-scm
    - python-ujson          # check
    - python-whatthepatch   # check
    - python-wheel
    - yapf                  # check
rundeps    :
    - autopep8
    - flake8
    - pydocstyle
    - pylint
    - python-docstring-to-markdown
    - python-jedi
    - python-lsp-jsonrpc
    - python-pluggy
    - python-rope
    - python-ujson
    - python-whatthepatch
    - yapf
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    skiptest=test_pyqt_completion
    skiptest+=' or pylint'
    %python3_test pytest3 -v -k "not (${skiptest})"
